name: Update Financial Prices

on:
  schedule:
    - cron: "0 */4 * * *" # Atualiza a cada 4 horas
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with financial prices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance

      - name: Fetch Stock Prices and Update README
        run: |
          python update_prices.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update financial prices in README"
          git push
